services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
        - ../secrets/certs/server.crt:/etc/nginx/certs/server.crt:ro
        - ../secrets/certs/server.key:/etc/nginx/certs/server.key:ro
        - /home/abonneau/data/wordpress_data:/var/www/html
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - my_network
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - /home/abonneau/data/wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_URL=${WORDPRESS_URL}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - my_network
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - /home/abonneau/data/mariadb_data:/var/lib/mysql
    networks:
      - my_network
volumes:
  mariadb_data:
  wordpress_data:
networks:
  my_network:
    driver: bridge