# version: "3.9"  # Version du format Docker Compose

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
        - ../secrets/certs/server.crt:/etc/nginx/certs/server.crt:ro
        - ../secrets/certs/server.key:/etc/nginx/certs/server.key:ro
        # - ./requirements/wordpress/wordpress_data:/var/www/html
    # volumes:
    #   - ./certs:/etc/nginx/certs  # Monter les certificats pour qu'ils soient persistants
    #   - ./default.conf:/etc/nginx/conf.d/default.conf:ro  # Monter la config NGINX en lecture seule
    #   - ./html:/var/www/html  # Optionnel : monter un dossier pour ton site web
    restart: unless-stopped   # Redémarrage automatique sauf si conteneur arrêté manuellement
    depends_on:
      - wordpress
    networks:
      - my_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=userpassword
      - WORDPRESS_DB_NAME=mydatabase
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - my_network

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword   # mot de passe root
      MYSQL_DATABASE: mydatabase           # nom de la base initiale
      MYSQL_USER: user                     # utilisateur secondaire
      MYSQL_PASSWORD: userpassword         # mot de passe de l'utilisateur
    volumes:
      - mariadb_data:/var/lib/mysql   # volume persistant pour les données
    networks:
      - my_network

volumes:
  mariadb_data:
  wordpress_data:

networks:
  my_network:
    driver: bridge