# version: "3.9"  # Version du format Docker Compose

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
        - ../secrets/certs/server.crt:/etc/nginx/certs/server.crt:ro
        - ../secrets/certs/server.key:/etc/nginx/certs/server.key:ro
    # volumes:
    #   - ./certs:/etc/nginx/certs  # Monter les certificats pour qu'ils soient persistants
    #   - ./default.conf:/etc/nginx/conf.d/default.conf:ro  # Monter la config NGINX en lecture seule
    #   - ./html:/var/www/html  # Optionnel : monter un dossier pour ton site web
    restart: unless-stopped   # Redémarrage automatique sauf si conteneur arrêté manuellement
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword   # mot de passe root
      MYSQL_DATABASE: mydatabase           # nom de la base initiale
      MYSQL_USER: user                     # utilisateur secondaire
      MYSQL_PASSWORD: userpassword         # mot de passe de l'utilisateur
    volumes:
      - ./requirements/mariadb/db_data:/var/lib/mysql   # volume persistant pour les données