services:
  nginx:
    build: 
      context: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
      - "8081:8081"
      - "8082:8082"
      - "3000:3000"
    volumes:
        - ../secrets/certs/server.crt:/etc/nginx/certs/server.crt:ro
        - ../secrets/certs/server.key:/etc/nginx/certs/server.key:ro
        - wordpress_data:/var/www/html/
        - static_website_data:/var/www/static
    restart: unless-stopped
    depends_on:
      - wordpress
      - static_website
      - adminer
      - portfolio
    networks:
      - network
  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_URL=${WORDPRESS_URL}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_RANDOM_USER=${WORDPRESS_RANDOM_USER}
      - WORDPRESS_RANDOM_PASSWORD=${WORDPRESS_RANDOM_PASSWORD}
      - WORDPRESS_RANDOM_EMAIL=${WORDPRESS_RANDOM_EMAIL}
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - network
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
  static_website:
    build: 
      context: ./requirements/static_website
    container_name: static_website
    image: static_website
    restart: unless-stopped
    volumes:
      - static_website_data:/var/www/html
    networks:
      - network

  portfolio:
    build: 
      context: ./requirements/portfolio
    container_name: portfolio
    image: portfolio
    restart: unless-stopped
    volumes:
      - portfolio_data:/app
    networks:
      - network
    expose:
      - "3000"

  ftp_server:
    build:
      context: ./requirements/ftp_server
    container_name: ftp_server
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/home/${FTP_USER}
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    restart: unless-stopped

  adminer:
    build: 
      context: ./requirements/adminer
    container_name: adminer
    networks:
      - network
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: volume
      device: /home/abonneau/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: volume
      device: /home/abonneau/data/wordpress_data
      o: bind
  static_website_data:
    driver: local
    driver_opts:
      type: volume
      device: /home/abonneau/data/static_website_data
      o: bind
  portfolio_data:
    driver: local
    driver_opts:
      type: volume
      device: /home/abonneau/data/portfolio_data
      o: bind
networks:
  network:
    driver: bridge