services:
  nginx:
    build: 
      context: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
      - "8081:8081"
    volumes:
        - ../secrets/certs/server.crt:/etc/nginx/certs/server.crt:ro
        - ../secrets/certs/server.key:/etc/nginx/certs/server.key:ro
        - wordpress_data:/var/www/html/
        - static_website_data:/var/www/static
    restart: unless-stopped
    depends_on:
      - wordpress
      - static_website
    networks:
      - network
  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_URL=${WORDPRESS_URL}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_RANDOM_USER=${WORDPRESS_RANDOM_USER}
      - WORDPRESS_RANDOM_PASSWORD=${WORDPRESS_RANDOM_PASSWORD}
      - WORDPRESS_RANDOM_EMAIL=${WORDPRESS_RANDOM_EMAIL}
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - network
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
  static_website:
    build: 
      context: ./requirements/static_website
    container_name: static_website
    image: static_website
    restart: unless-stopped
    volumes:
      - static_website_data:/var/www/html
    networks:
      - network


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: volume
      device: /home/abonneau/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: volume
      device: /home/abonneau/data/wordpress_data
      o: bind
  static_website_data:
    driver: local
    driver_opts:
      type: volume
      device: /home/abonneau/data/static_website_data
      o: bind
networks:
  network:
    driver: bridge